name:               "Lisa"
description:        "General thoughts and specific hacks from the domains of science, cognition and programming"

blog_url:                "https://LisaSchwetlick.de/blog"
lisa_url:                "https://LisaSchwetlick.de/"


blogurl:            ""
author:             "Lisa"
email:              "mail@lisaschwetlick.de"
twitter:            "Enemy_Anemone"
github:             "lschwetlick"
# pinterest:          "jhondoe"
# linkedin:           "jhondoe"
facebook:           "AnEnemyAnemone"

# disqus_shortname:   "thinker3197"

avatar_img:         "/resources/images/lisaXS.jpg"
background:         "/resources/images/lisaXS.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            "https://lisaschwetlick.de/blog/"
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/blog/about/index.html"
  # - name:           "Home"
  #   href:           ""

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-paginate